name: Build, Check And Deploy to Dev

on:
  push:
    branches:
      - fix/imagery-removal-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: npm install, and build
      run: |
        printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" >> ~/.npmrc
        npm install
        npm run dev-build
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        VUE_APP_CYCLOMEDIA_API_KEY: ${{ secrets.VUE_APP_CYCLOMEDIA_API_KEY }}
        VUE_APP_CYCLOMEDIA_PASSWORD: ${{ secrets.VUE_APP_CYCLOMEDIA_PASSWORD }}
        VUE_APP_CYCLOMEDIA_USERNAME: ${{ secrets.VUE_APP_CYCLOMEDIA_USERNAME }}
        VUE_APP_GATEKEEPER_KEY: ${{ secrets.VUE_APP_GATEKEEPER_KEY }}

    - name: Deploy to Dev s3
      run: |
        aws s3 sync dist s3://$AWS_S3_BUCKET --region us-east-1 --delete
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_S3_BUCKET: property-data-explorer
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: MS Teams Card
      uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        environment: ${{ steps.global-vars.outputs.aws_env_prefix }}
        card-layout-start: cozy
